# Les fichiers
* Répertoire absolu et relatif
* Chemin d'accès
* Fichier texte (c'est une chaine de caractère)
* Lecture/écriture
* Format JSON

In [1]:
!pwd
# Sous windows !cd => c:\Users\login\

/home/pierre/Enseignement/2024/Python1/cours/cours3


In [ ]:
filename = "/home/pierre/Enseignement/2024/Python1/cours/cours3/Fichiers.ipynb"
filename = "Fichiers.ipynb"

In [3]:
current_dir = "/home/pierre/Enseignement/2024/Python1/cours/cours3"

In [7]:
# Chemin relatif
import os
print(os.listdir('.'))
print(os.listdir('data/'))
print(os.listdir('../cours1'))

['tableaux nD.ipynb', 'data.txt', 'erreurs.ipynb', 'Fichiers.ipynb', 'data', 'Ajustement (fit).ipynb']
['data.txt']
['Bases de python et utilisation de numpy.ipynb', 'test_long.txt', 'test.txt', 'ma_figure.pdf', 'ma_figure.svg', 'test_long.npy']


In [8]:
file = 'data/test_python.txt'
fd = open(file, 'w')
fd.write('Bonjour\n')
fd.close()

In [9]:
with open(file, 'a') as fd:
    fd.write('Au revoir')

In [10]:
with open(file) as fd:
    print(fd.read())

Bonjour
Au revoir


In [11]:
with open(file) as fd:
    lines = fd.readlines()
    
for line in lines:
    print(line.strip()) # strip pour enlever le \n

Bonjour
Au revoir


## JSON
* Permet d'enregistrer une liste ou un dictionnaire
* Fichier lisible par un humain

In [12]:
import json

personne_1 = {"nom":"Dupont", "age":13}
personne_2 = {"nom":"Dubois", "age":34}

annuaire = [personne_1, personne_2]

file = 'test.json'
with open(file, "w") as f:
    json.dump(annuaire, f, indent=2)
    

In [13]:
with open(file) as f:
    annuaire = json.load(f)
print(annuaire)    
    


[{'nom': 'Dupont', 'age': 13}, {'nom': 'Dubois', 'age': 34}]


# Numpy

In [14]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# save et savetxt

In [25]:
x = np.random.rand(100000, 5)
#x

In [26]:
np.save('test.npy', x)

In [27]:
np.savetxt('test.txt', x)

In [28]:
%%time 
np.load('test.npy')

CPU times: user 1.27 ms, sys: 4.48 ms, total: 5.75 ms
Wall time: 5 ms


array([[0.67569117, 0.81770461, 0.15917832, 0.96429851, 0.13139772],
       [0.08773025, 0.06251673, 0.11822542, 0.69139755, 0.15471339],
       [0.60033843, 0.16296808, 0.10338403, 0.22638167, 0.79134292],
       ...,
       [0.30445556, 0.90195789, 0.84638789, 0.94748221, 0.13345051],
       [0.84046908, 0.30917057, 0.71176153, 0.50192863, 0.30832341],
       [0.02515209, 0.63825433, 0.62988103, 0.16696348, 0.45145068]])

In [29]:
%%time 
np.loadtxt('test.txt')

CPU times: user 313 ms, sys: 13 ms, total: 326 ms
Wall time: 323 ms


array([[0.67569117, 0.81770461, 0.15917832, 0.96429851, 0.13139772],
       [0.08773025, 0.06251673, 0.11822542, 0.69139755, 0.15471339],
       [0.60033843, 0.16296808, 0.10338403, 0.22638167, 0.79134292],
       ...,
       [0.30445556, 0.90195789, 0.84638789, 0.94748221, 0.13345051],
       [0.84046908, 0.30917057, 0.71176153, 0.50192863, 0.30832341],
       [0.02515209, 0.63825433, 0.62988103, 0.16696348, 0.45145068]])

In [30]:
np.loadtxt?

In [32]:
l = [[1, 2], [2, 5], [5, 6]]

a, b, c = l

In [34]:
a, b, c, d, e = np.loadtxt('test.txt', unpack=True)

In [35]:
a

array([0.67569117, 0.08773025, 0.60033843, ..., 0.30445556, 0.84046908,
       0.02515209])